#!/bin/sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################
APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
